(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _sapper_app__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @sapper/app */ "./src/node_modules/@sapper/app.mjs");
/* src\routes\index.svelte generated by Svelte v3.23.2 */



const file = "src\\routes\\index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1r13gch-style";
	style.textContent = ".container.svelte-1r13gch.svelte-1r13gch{grid-column-start:2;grid-column-end:3;display:flex;flex-direction:column;align-items:center;max-width:1200px;background-color:white}.heroPhoto.svelte-1r13gch.svelte-1r13gch{margin:0 0}.details.svelte-1r13gch.svelte-1r13gch{background-color:rgb(248, 243, 237);padding:60px 0\t80px 0;margin:60px 0 60px 0;width:100%}.details-columns.svelte-1r13gch.svelte-1r13gch{display:flex;flex-wrap:wrap}.icons-container.svelte-1r13gch.svelte-1r13gch{display:flex;justify-content:center;margin-top:30px}.icons.svelte-1r13gch.svelte-1r13gch{display:flex;flex-wrap:wrap;background-color:white}.icon.svelte-1r13gch.svelte-1r13gch{display:flex;flex-direction:column;align-items:center;justify-content:space-between}.fig.svelte-1r13gch.svelte-1r13gch{display:flex;justify-content:center;margin:20px 40px}.fig.svelte-1r13gch>img.svelte-1r13gch{width:auto}.text.svelte-1r13gch.svelte-1r13gch{display:flex;flex-direction:column;align-items:center;margin-bottom:10px}.confirm.svelte-1r13gch.svelte-1r13gch{padding-bottom:20px;margin-bottom:20px;width:100%;text-align:center}h2.svelte-1r13gch.svelte-1r13gch,h3.svelte-1r13gch.svelte-1r13gch,p.svelte-1r13gch.svelte-1r13gch{margin:10px 40px}h1.svelte-1r13gch.svelte-1r13gch{font-size:2.8em;text-align:center;font-weight:600;margin:0 0 0.5em 0}h2.svelte-1r13gch.svelte-1r13gch{margin-bottom:20px}h3.svelte-1r13gch.svelte-1r13gch{font-weight:600}img.svelte-1r13gch.svelte-1r13gch{width:100%;margin:0 0 0 0}@media(min-width: 480px){h1.svelte-1r13gch.svelte-1r13gch{font-size:4em;margin-top:20px}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBzdG9yZXMgfSBmcm9tICdAc2FwcGVyL2FwcCc7XG5cdGNvbnN0IHsgcHJlbG9hZGluZywgcGFnZSwgc2Vzc2lvbiB9ID0gc3RvcmVzKCk7XG5cbiAgICBjb25zdCB0b1RpdGxlQ2FzZSA9IChwaHJhc2UpID0+IHtcblx0XHRsZXQgcmVzID0gXCJcIlxuXHRcdGlmIChwaHJhc2UpIHtcblx0XHRcdHJlcyA9IHBocmFzZVxuICAgICAgICAgICAgLnRvTG93ZXJDYXNlKClcbiAgICAgICAgICAgIC5zcGxpdCgnICcpXG4gICAgICAgICAgICAubWFwKHdvcmQgPT4gd29yZC5jaGFyQXQoMCkudG9VcHBlckNhc2UoKSArIHdvcmQuc2xpY2UoMSkpXG5cdFx0XHQuam9pbignLCAnKTtcblx0XHR9XG5cdFx0cmV0dXJuIHJlcztcblx0fTtcblx0Y29uc3QgY2hvb3NlUGx1cmFsID0gbmFtZXMgPT4gbmFtZXMgJiYgKG5hbWVzLnNwbGl0KCcgJykubGVuZ3RoID4gMSkgPyBcIkthbGxpZFwiIDogXCJLYWxsaXNcIjtcblxuICAgICQ6IG5hbWVzID0gJHBhZ2UucXVlcnlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5cdC5jb250YWluZXIge1xuXHRcdGdyaWQtY29sdW1uLXN0YXJ0OiAyO1xuXHRcdGdyaWQtY29sdW1uLWVuZDogMztcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXgtd2lkdGg6IDEyMDBweDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcblx0fVxuXHRcblx0Lmhlcm9QaG90byB7XG5cdFx0bWFyZ2luOiAwIDA7XG5cdH1cblxuXHQuZGV0YWlscyB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiKDI0OCwgMjQzLCAyMzcpO1xuXHRcdHBhZGRpbmc6IDYwcHggMFx0ODBweCAwO1xuXHRcdG1hcmdpbjogNjBweCAwIDYwcHggMDtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5kZXRhaWxzLWNvbHVtbnMge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC13cmFwOiB3cmFwO1xuXHR9XG5cblx0Lmljb25zLWNvbnRhaW5lciB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cdC5pY29ucyB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRmbGV4LXdyYXA6IHdyYXA7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogd2hpdGU7XG5cdH1cblxuXHQuaWNvbiB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHR9XG5cblx0LmZpZyB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRtYXJnaW46IDIwcHggNDBweDtcblx0fVxuXG5cdC5maWcgPiBpbWcge1xuXHRcdHdpZHRoOiBhdXRvO1xuXHR9XG5cdC50ZXh0IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tYm90dG9tOiAxMHB4O1xuXHR9XG5cblx0LmNvbmZpcm0ge1xuXHRcdHBhZGRpbmctYm90dG9tOiAyMHB4O1xuXHRcdG1hcmdpbi1ib3R0b206IDIwcHg7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdFx0dGV4dC1hbGlnbjogY2VudGVyO1xuXHR9XG5cblx0aDIsIGgzLCBwIHtcblx0XHRtYXJnaW46IDEwcHggNDBweDtcdFxuXHR9XG5cblx0aDEge1xuXHRcdGZvbnQtc2l6ZTogMi44ZW07XG5cdFx0dGV4dC1hbGlnbjogY2VudGVyO1xuXHRcdGZvbnQtd2VpZ2h0OiA2MDA7XG5cdFx0bWFyZ2luOiAwIDAgMC41ZW0gMDtcblx0fVxuXHRcblx0aDIge1xuXHRcdG1hcmdpbi1ib3R0b206IDIwcHg7XG5cdH1cblxuXHRoMyB7XG5cdFx0Zm9udC13ZWlnaHQ6IDYwMDtcblx0fVxuXG5cdGltZyB7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdFx0bWFyZ2luOiAwIDAgMCAwO1xuXHR9XG5cblxuXHRAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcblx0XHRoMSB7XG5cdFx0XHRmb250LXNpemU6IDRlbTtcblx0XHRcdG1hcmdpbi10b3A6IDIwcHg7XG5cdFx0fVxuXHR9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5BaXZvIGphIExhdXJhIHB1bG1hZDwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cblx0PGgxPntjaG9vc2VQbHVyYWwobmFtZXMubmltaSl9IHt0b1RpdGxlQ2FzZShuYW1lcy5uaW1pKX08L2gxPlxuXG5cdDxpbWcgYWx0PSdLdXRzZSBwaWx0JyBzcmM9J2t1dHNlLnBuZyc+XG5cblx0PGRpdiBjbGFzcz1cImRldGFpbHNcIj5cblx0XHQ8aDI+UHVsbWFkZSB0b2ltdW1pbmU8L2gyPlxuXHRcdDxkaXYgY2xhc3M9XCJkZXRhaWxzLWNvbHVtbnNcIj5cblx0XHRcdDxkaXY+XG5cdFx0XHRcdDxoMz5MYXVsYXR1czwvaDM+XG5cdFx0XHRcdDxwPjE1OjMwIC0gw5VubmVwYWxlZSAoUMOkcm51IG1udCA2NywgVGFsbGlubik8L3A+XG5cdFx0XHRcdDxwPjE1OjQ1IC0gUGlsZGlzdGFtaW5lIMOVbm5lcGFsZWUgdHJlcGlsLjwvcD5cblx0XHRcdFx0PHA+TcOkcmt1cyEgSnV1bmkgc2Vpc3VnYSBsdWJhdGFrc2UgbGF1bGF0dXNlIHJ1dW1pIGt1bmkgMzAgaW5pbWVzdCE8L3A+XG5cdFx0XHQ8L2Rpdj5cblx0XHRcdDxkaXY+XG5cdFx0XHRcdDxoMz5QdWxtYXBpZHU8L2gzPlxuXHRcdFx0XHQ8cD4xNzowMCBHbGVobmkgbG9zcyAoVmFuYS1NdXN0YW3DpGUgNDgsIE7DtW1tZSwgVGFsbGlubik8L3A+XG5cdFx0XHRcdDxwPjE4OjAwIMOVaHR1c8O2w7ZrLiBKw6RyZ25lYiBtdXVzaWthLCB0YW50cyBqYSB0cmFsbC48L3A+XG5cdFx0XHRcdDxwPjAxOjAwIFBlbyBvcmllbnRlZXJ1diBsw7VwcC48L3A+XG5cdFx0XHQ8L2Rpdj5cblx0XHRcblx0XHQ8L2Rpdj5cblx0XHQ8ZGl2IGNsYXNzPVwiaWNvbnMtY29udGFpbmVyXCI+XG5cdFx0XHQ8ZGl2IGNsYXNzPVwiaWNvbnNcIj5cblx0XHRcdFx0PGRpdiBjbGFzcz1cImljb25cIj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwiZmlnXCI+XG5cdFx0XHRcdFx0XHQ8aW1nIGFsdD0ndHNlcmVtb29uaWEnIHNyYz0ndHNlcmVtb29uaWEucG5nJz5cblx0XHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwidGV4dFwiPlxuXHRcdFx0XHRcdFx0PHNwYW4+TGF1bGF0dXM8L3NwYW4+XG5cdFx0XHRcdFx0XHQ8c3Bhbj4xNTozMDwvc3Bhbj5cblx0XHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdDxkaXYgY2xhc3M9XCJpY29uXCI+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cImZpZ1wiPlxuXHRcdFx0XHRcdFx0PGltZyBhbHQ9J3RlcnZpdHVzam9vaycgc3JjPSd0ZXJ2aXR1c2pvb2sucG5nJz5cblx0XHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwidGV4dFwiPlxuXHRcdFx0XHRcdFx0PHNwYW4+VGVydml0dXNqb29rPC9zcGFuPlxuXHRcdFx0XHRcdFx0PHNwYW4+MTc6MTU8L3NwYW4+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHQ8ZGl2IGNsYXNzPVwiaWNvblwiPlxuXHRcdFx0XHRcdDxkaXYgY2xhc3M9XCJmaWdcIj5cblx0XHRcdFx0XHRcdDxpbWcgYWx0PSfDlWh0dXPDtsO2aycgc3JjPSdvaHR1c29vay5wbmcnPlxuXHRcdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHRcdDxkaXYgY2xhc3M9XCJ0ZXh0XCI+XG5cdFx0XHRcdFx0XHQ8c3Bhbj7DlWh0dXPDtsO2azwvc3Bhbj5cblx0XHRcdFx0XHRcdDxzcGFuPjE4OjAwPC9zcGFuPlxuXHRcdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0PGRpdiBjbGFzcz1cImljb25cIj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwiZmlnXCI+XG5cdFx0XHRcdFx0XHQ8aW1nIGFsdD0nTXV1c2lrYSBqYSB0YW50cycgc3JjPSdtdXVzaWthLnBuZyc+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cInRleHRcIj5cblx0XHRcdFx0XHRcdDxzcGFuPkLDpG5kLCB0YW50c3Vww7VyYW5kPC9zcGFuPlxuXHRcdFx0XHRcdFx0PHNwYW4+MjA6MDA8L3NwYW4+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdDwvZGl2PlxuXHRcdFx0PC9kaXY+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdDxkaXYgY2xhc3M9XCJjb25maXJtXCI+XG5cdFx0PGgyPk9zYWxlbWlzZXN0IHRlYXZpdGFtaW5lPC9oMj5cblx0XHQ8cD7DhHNqYSBtw7bDtmR1bnVkIGVyaW9sbHVrb3JyYSB0w7V0dHUgb24gcHVsbSBvbiBwbGFubmVyaXR1ZCBvbGVtYSBwaWdlbSB2w6Rpa2UuIEt1dHN1bWUgdmFpZCBzdWd1bGFzaSBuaW5nIGzDpGhlZGFzZW1haWQgc8O1cHJ1LjwvcD5cblx0XHQ8aDM+UGFsdW4gdGVhdml0YSBvbWEgb3NhbGVtaXNlc3QgZXNpbWVzZWwgdsO1aW1hbHVzZWwsIHNvb3ZpdGF2YWx0IHbDpGhlbWFzdGkgZW5uZSAxLiBqdXVsaXQuPC9oMz5cblxuXHQ8L2Rpdj5cblxuXHQ8ZGl2IGNsYXNzPVwiaGVyb1Bob3RvXCI+XG5cdFx0PGltZyBhbHQ9J0Fpdm8gamEgTGF1cmEnIHNyYz0neWxlbWluZS5qcGcnPlxuXHQ8L2Rpdj5cblxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBcUJDLFVBQVUsOEJBQUMsQ0FBQyxBQUNYLGlCQUFpQixDQUFFLENBQUMsQ0FDcEIsZUFBZSxDQUFFLENBQUMsQ0FDbEIsT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxDQUN0QixXQUFXLENBQUUsTUFBTSxDQUNuQixTQUFTLENBQUUsTUFBTSxDQUNqQixnQkFBZ0IsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFFRCxVQUFVLDhCQUFDLENBQUMsQUFDWCxNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQUFDWixDQUFDLEFBRUQsUUFBUSw4QkFBQyxDQUFDLEFBQ1QsZ0JBQWdCLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDcEMsT0FBTyxDQUFFLElBQUksQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FDdEIsTUFBTSxDQUFFLElBQUksQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FDckIsS0FBSyxDQUFFLElBQUksQUFDWixDQUFDLEFBRUQsZ0JBQWdCLDhCQUFDLENBQUMsQUFDakIsT0FBTyxDQUFFLElBQUksQ0FDYixTQUFTLENBQUUsSUFBSSxBQUNoQixDQUFDLEFBRUQsZ0JBQWdCLDhCQUFDLENBQUMsQUFDakIsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixVQUFVLENBQUUsSUFBSSxBQUNqQixDQUFDLEFBQ0QsTUFBTSw4QkFBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLElBQUksQ0FDYixTQUFTLENBQUUsSUFBSSxDQUNmLGdCQUFnQixDQUFFLEtBQUssQUFDeEIsQ0FBQyxBQUVELEtBQUssOEJBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsV0FBVyxDQUFFLE1BQU0sQ0FDbkIsZUFBZSxDQUFFLGFBQWEsQUFDL0IsQ0FBQyxBQUVELElBQUksOEJBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsTUFBTSxDQUFFLElBQUksQ0FBQyxJQUFJLEFBQ2xCLENBQUMsQUFFRCxtQkFBSSxDQUFHLEdBQUcsZUFBQyxDQUFDLEFBQ1gsS0FBSyxDQUFFLElBQUksQUFDWixDQUFDLEFBQ0QsS0FBSyw4QkFBQyxDQUFDLEFBQ04sT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxDQUN0QixXQUFXLENBQUUsTUFBTSxDQUNuQixhQUFhLENBQUUsSUFBSSxBQUNwQixDQUFDLEFBRUQsUUFBUSw4QkFBQyxDQUFDLEFBQ1QsY0FBYyxDQUFFLElBQUksQ0FDcEIsYUFBYSxDQUFFLElBQUksQ0FDbkIsS0FBSyxDQUFFLElBQUksQ0FDWCxVQUFVLENBQUUsTUFBTSxBQUNuQixDQUFDLEFBRUQsZ0NBQUUsQ0FBRSxnQ0FBRSxDQUFFLENBQUMsOEJBQUMsQ0FBQyxBQUNWLE1BQU0sQ0FBRSxJQUFJLENBQUMsSUFBSSxBQUNsQixDQUFDLEFBRUQsRUFBRSw4QkFBQyxDQUFDLEFBQ0gsU0FBUyxDQUFFLEtBQUssQ0FDaEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsQUFDcEIsQ0FBQyxBQUVELEVBQUUsOEJBQUMsQ0FBQyxBQUNILGFBQWEsQ0FBRSxJQUFJLEFBQ3BCLENBQUMsQUFFRCxFQUFFLDhCQUFDLENBQUMsQUFDSCxXQUFXLENBQUUsR0FBRyxBQUNqQixDQUFDLEFBRUQsR0FBRyw4QkFBQyxDQUFDLEFBQ0osS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxBQUNoQixDQUFDLEFBR0QsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUMxQixFQUFFLDhCQUFDLENBQUMsQUFDSCxTQUFTLENBQUUsR0FBRyxDQUNkLFVBQVUsQ0FBRSxJQUFJLEFBQ2pCLENBQUMsQUFDRixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let div20;
	let h1;
	let t1_value = /*choosePlural*/ ctx[3](/*names*/ ctx[0].nimi) + "";
	let t1;
	let t2;
	let t3_value = /*toTitleCase*/ ctx[2](/*names*/ ctx[0].nimi) + "";
	let t3;
	let t4;
	let img0;
	let img0_src_value;
	let t5;
	let div17;
	let h20;
	let t6;
	let t7;
	let div2;
	let div0;
	let h30;
	let t8;
	let t9;
	let p0;
	let t10;
	let t11;
	let p1;
	let t12;
	let t13;
	let p2;
	let t14;
	let t15;
	let div1;
	let h31;
	let t16;
	let t17;
	let p3;
	let t18;
	let t19;
	let p4;
	let t20;
	let t21;
	let p5;
	let t22;
	let t23;
	let div16;
	let div15;
	let div5;
	let div3;
	let img1;
	let img1_src_value;
	let t24;
	let div4;
	let span0;
	let t25;
	let t26;
	let span1;
	let t27;
	let t28;
	let div8;
	let div6;
	let img2;
	let img2_src_value;
	let t29;
	let div7;
	let span2;
	let t30;
	let t31;
	let span3;
	let t32;
	let t33;
	let div11;
	let div9;
	let img3;
	let img3_src_value;
	let t34;
	let div10;
	let span4;
	let t35;
	let t36;
	let span5;
	let t37;
	let t38;
	let div14;
	let div12;
	let img4;
	let img4_src_value;
	let t39;
	let div13;
	let span6;
	let t40;
	let t41;
	let span7;
	let t42;
	let t43;
	let div18;
	let h21;
	let t44;
	let t45;
	let p6;
	let t46;
	let t47;
	let h32;
	let t48;
	let t49;
	let div19;
	let img5;
	let img5_src_value;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pulmade toimumine");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Laulatus");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("15:30 - Õnnepalee (Pärnu mnt 67, Tallinn)");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("15:45 - Pildistamine Õnnepalee trepil.");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Märkus! Juuni seisuga lubatakse laulatuse ruumi kuni 30 inimest!");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pulmapidu");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("17:00 Glehni loss (Vana-Mustamäe 48, Nõmme, Tallinn)");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("18:00 Õhtusöök. Järgneb muusika, tants ja trall.");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("01:00 Peo orienteeruv lõpp.");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Laulatus");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("15:30");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Tervitusjook");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("17:15");
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Õhtusöök");
			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("18:00");
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Bänd, tantsupõrand");
			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("20:00");
			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Osalemisest teavitamine");
			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Äsja möödunud eriollukorra tõttu on pulm on planneritud olema pigem väike. Kutsume vaid sugulasi ning lähedasemaid sõpru.");
			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t48 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Palun teavita oma osalemisest esimesel võimalusel, soovitavalt vähemasti enne 1. juulit.");
			t49 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1s2tmaq\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div20);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t1_value);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(h1_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t3_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div20_nodes);
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "IMG", { alt: true, src: true, class: true });
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div20_nodes);
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "DIV", { class: true });
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);
			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "H2", { class: true });
			var h20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h20);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h20_nodes, "Pulmade toimumine");
			h20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", {});
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H3", { class: true });
			var h30_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h30);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h30_nodes, "Laulatus");
			h30_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "15:30 - Õnnepalee (Pärnu mnt 67, Tallinn)");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "15:45 - Pildistamine Õnnepalee trepil.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Märkus! Juuni seisuga lubatakse laulatuse ruumi kuni 30 inimest!");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "H3", { class: true });
			var h31_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h31);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h31_nodes, "Pulmapidu");
			h31_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p3);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p3_nodes, "17:00 Glehni loss (Vana-Mustamäe 48, Nõmme, Tallinn)");
			p3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p4);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p4_nodes, "18:00 Õhtusöök. Järgneb muusika, tants ja trall.");
			p4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p5);
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p5_nodes, "01:00 Peo orienteeruv lõpp.");
			p5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "DIV", { class: true });
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "IMG", { alt: true, src: true, class: true });
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "SPAN", {});
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, "Laulatus");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div4_nodes);
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "SPAN", {});
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "15:30");
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div15_nodes);
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);
			img2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "IMG", { alt: true, src: true, class: true });
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div8_nodes);
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);
			span2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "SPAN", {});
			var span2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span2);
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span2_nodes, "Tervitusjook");
			span2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div7_nodes);
			span3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "SPAN", {});
			var span3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span3);
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span3_nodes, "17:15");
			span3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div15_nodes);
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "DIV", { class: true });
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);
			img3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div9_nodes, "IMG", { alt: true, src: true, class: true });
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div11_nodes);
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "DIV", { class: true });
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);
			span4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "SPAN", {});
			var span4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span4);
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span4_nodes, "Õhtusöök");
			span4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div10_nodes);
			span5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "SPAN", {});
			var span5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span5);
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span5_nodes, "18:00");
			span5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div15_nodes);
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "DIV", { class: true });
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);
			img4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "IMG", { alt: true, src: true, class: true });
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div14_nodes);
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "DIV", { class: true });
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);
			span6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "SPAN", {});
			var span6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span6);
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span6_nodes, "Bänd, tantsupõrand");
			span6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div13_nodes);
			span7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "SPAN", {});
			var span7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span7);
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span7_nodes, "20:00");
			span7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div20_nodes);
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "DIV", { class: true });
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);
			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "H2", { class: true });
			var h21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h21);
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h21_nodes, "Osalemisest teavitamine");
			h21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "P", { class: true });
			var p6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p6);
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p6_nodes, "Äsja möödunud eriollukorra tõttu on pulm on planneritud olema pigem väike. Kutsume vaid sugulasi ning lähedasemaid sõpru.");
			p6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "H3", { class: true });
			var h32_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h32);
			t48 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h32_nodes, "Palun teavita oma osalemisest esimesel võimalusel, soovitavalt vähemasti enne 1. juulit.");
			h32_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t49 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div20_nodes);
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "DIV", { class: true });
			var div19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div19);
			img5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div19_nodes, "IMG", { alt: true, src: true, class: true });
			div19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Aivo ja Laura pulmad";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 127, 1, 1898);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "alt", "Kutse pilt");
			if (img0.src !== (img0_src_value = "kutse.png")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "src", img0_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 129, 1, 1962);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h20, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h20, file, 132, 2, 2027);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h30, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h30, file, 135, 4, 2099);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 136, 4, 2121);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 137, 4, 2174);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 138, 4, 2224);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 134, 3, 2089);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h31, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h31, file, 141, 4, 2319);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p3, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p3, file, 142, 4, 2342);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p4, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p4, file, 143, 4, 2406);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p5, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p5, file, 144, 4, 2466);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 140, 3, 2309);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "details-columns svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 133, 2, 2056);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "alt", "tseremoonia");
			if (img1.src !== (img1_src_value = "tseremoonia.png")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "src", img1_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 152, 6, 2630);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "fig svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 151, 5, 2606);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 155, 6, 2718);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 156, 6, 2746);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "text svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 154, 5, 2693);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "icon svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 150, 4, 2582);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img2, "alt", "tervitusjook");
			if (img2.src !== (img2_src_value = "tervitusjook.png")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img2, "src", img2_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img2, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img2, file, 161, 6, 2840);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div6, "class", "fig svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 160, 5, 2816);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span2, file, 164, 6, 2930);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span3, file, 165, 6, 2962);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div7, "class", "text svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 163, 5, 2905);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div8, "class", "icon svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 159, 4, 2792);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img3, "alt", "Õhtusöök");
			if (img3.src !== (img3_src_value = "ohtusook.png")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img3, "src", img3_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img3, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img3, file, 170, 6, 3056);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div9, "class", "fig svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 169, 5, 3032);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span4, file, 173, 6, 3138);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span5, file, 174, 6, 3166);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div10, "class", "text svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 172, 5, 3113);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div11, "class", "icon svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 168, 4, 3008);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img4, "alt", "Muusika ja tants");
			if (img4.src !== (img4_src_value = "muusika.png")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img4, "src", img4_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img4, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img4, file, 179, 6, 3260);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div12, "class", "fig svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 178, 5, 3236);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span6, file, 182, 6, 3349);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span7, file, 183, 6, 3387);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div13, "class", "text svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 181, 5, 3324);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div14, "class", "icon svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 177, 4, 3212);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div15, "class", "icons svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 149, 3, 2558);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div16, "class", "icons-container svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 148, 2, 2525);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div17, "class", "details svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 131, 1, 2003);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h21, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h21, file, 191, 2, 3482);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p6, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p6, file, 192, 2, 3517);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h32, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h32, file, 193, 2, 3648);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div18, "class", "confirm svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 190, 1, 3458);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img5, "alt", "Aivo ja Laura");
			if (img5.src !== (img5_src_value = "ylemine.jpg")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img5, "src", img5_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img5, "class", "svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img5, file, 198, 2, 3783);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div19, "class", "heroPhoto svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div19, file, 197, 1, 3757);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div20, "class", "container svelte-1r13gch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div20, file, 126, 0, 1873);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div20, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, h20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h20, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h30, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, h31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h31, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p3, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p4, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p5, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div6, img2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, span2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span2, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, span3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span3, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, t33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div9, img3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, t34);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, span4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span4, t35);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, t36);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, span5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span5, t37);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, t38);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, img4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, t39);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, span6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span6, t40);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, t41);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, span7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span7, t42);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, t43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, div18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, h21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h21, t44);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t45);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, p6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p6, t46);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t47);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, h32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h32, t48);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, t49);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, div19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div19, img5);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*names*/ 1 && t1_value !== (t1_value = /*choosePlural*/ ctx[3](/*names*/ ctx[0].nimi) + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			if (dirty & /*names*/ 1 && t3_value !== (t3_value = /*toTitleCase*/ ctx[2](/*names*/ ctx[0].nimi) + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div20);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $page;
	const { preloading, page, session } = Object(_sapper_app__WEBPACK_IMPORTED_MODULE_1__["stores"])();
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(page, "page");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, page, value => $$invalidate(4, $page = value));

	const toTitleCase = phrase => {
		let res = "";

		if (phrase) {
			res = phrase.toLowerCase().split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(", ");
		}

		return res;
	};

	const choosePlural = names => names && names.split(" ").length > 1
	? "Kallid"
	: "Kallis";

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);

	$$self.$capture_state = () => ({
		stores: _sapper_app__WEBPACK_IMPORTED_MODULE_1__["stores"],
		preloading,
		page,
		session,
		toTitleCase,
		choosePlural,
		names,
		$page
	});

	$$self.$inject_state = $$props => {
		if ("names" in $$props) $$invalidate(0, names = $$props.names);
	};

	let names;

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*$page*/ 16) {
			$: $$invalidate(0, names = $page.query);
		}
	};

	return [names, page, toTitleCase, choosePlural];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1r13gch-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7O0FBQ3lDOzs7Ozs7Ozs7Ozs7OztpQ0E4SG5DLEdBQVksY0FBQyxHQUFLLElBQUMsSUFBSTs7O2dDQUFJLEdBQVcsY0FBQyxHQUFLLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3RUFBakQsR0FBWSxjQUFDLEdBQUssSUFBQyxJQUFJO3VFQUFJLEdBQVcsY0FBQyxHQUFLLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7U0E3SDlDLFVBQVUsRUFBRSxJQUFJLEVBQUUsT0FBTyxLQUFLLDBEQUFNOzs7O09BRW5DLFdBQVcsR0FBSSxNQUFNO01BQ3pCLEdBQUcsR0FBRyxFQUFFOztNQUNSLE1BQU07R0FDVCxHQUFHLEdBQUcsTUFBTSxDQUNGLFdBQVcsR0FDWCxLQUFLLENBQUMsR0FBRyxFQUNULEdBQUcsQ0FBQyxJQUFJLElBQUksSUFBSSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsV0FBVyxLQUFLLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQyxHQUNoRSxJQUFJLENBQUMsSUFBSTs7O1NBRUosR0FBRzs7O09BRUwsWUFBWSxHQUFHLEtBQUssSUFBSSxLQUFLLElBQUssS0FBSyxDQUFDLEtBQUssQ0FBQyxHQUFHLEVBQUUsTUFBTSxHQUFHLENBQUM7R0FBSSxRQUFRO0dBQUcsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztHQUV2RixDQUFDLGtCQUFFLEtBQUssR0FBRyxLQUFLLENBQUMsS0FBSyIsImZpbGUiOiJiNjBiYTIxYWU4MzM0MjJiYjExZi9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gICAgaW1wb3J0IHsgc3RvcmVzIH0gZnJvbSAnQHNhcHBlci9hcHAnO1xuXHRjb25zdCB7IHByZWxvYWRpbmcsIHBhZ2UsIHNlc3Npb24gfSA9IHN0b3JlcygpO1xuXG4gICAgY29uc3QgdG9UaXRsZUNhc2UgPSAocGhyYXNlKSA9PiB7XG5cdFx0bGV0IHJlcyA9IFwiXCJcblx0XHRpZiAocGhyYXNlKSB7XG5cdFx0XHRyZXMgPSBwaHJhc2VcbiAgICAgICAgICAgIC50b0xvd2VyQ2FzZSgpXG4gICAgICAgICAgICAuc3BsaXQoJyAnKVxuICAgICAgICAgICAgLm1hcCh3b3JkID0+IHdvcmQuY2hhckF0KDApLnRvVXBwZXJDYXNlKCkgKyB3b3JkLnNsaWNlKDEpKVxuXHRcdFx0LmpvaW4oJywgJyk7XG5cdFx0fVxuXHRcdHJldHVybiByZXM7XG5cdH07XG5cdGNvbnN0IGNob29zZVBsdXJhbCA9IG5hbWVzID0+IG5hbWVzICYmIChuYW1lcy5zcGxpdCgnICcpLmxlbmd0aCA+IDEpID8gXCJLYWxsaWRcIiA6IFwiS2FsbGlzXCI7XG5cbiAgICAkOiBuYW1lcyA9ICRwYWdlLnF1ZXJ5XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuXHQuY29udGFpbmVyIHtcblx0XHRncmlkLWNvbHVtbi1zdGFydDogMjtcblx0XHRncmlkLWNvbHVtbi1lbmQ6IDM7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cdFx0bWF4LXdpZHRoOiAxMjAwcHg7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogd2hpdGU7XG5cdH1cblx0XG5cdC5oZXJvUGhvdG8ge1xuXHRcdG1hcmdpbjogMCAwO1xuXHR9XG5cblx0LmRldGFpbHMge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYigyNDgsIDI0MywgMjM3KTtcblx0XHRwYWRkaW5nOiA2MHB4IDBcdDgwcHggMDtcblx0XHRtYXJnaW46IDYwcHggMCA2MHB4IDA7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdH1cblxuXHQuZGV0YWlscy1jb2x1bW5zIHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtd3JhcDogd3JhcDtcblx0fVxuXG5cdC5pY29ucy1jb250YWluZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0bWFyZ2luLXRvcDogMzBweDtcblx0fVxuXHQuaWNvbnMge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC13cmFwOiB3cmFwO1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHdoaXRlO1xuXHR9XG5cblx0Lmljb24ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2Vlbjtcblx0fVxuXG5cdC5maWcge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0bWFyZ2luOiAyMHB4IDQwcHg7XG5cdH1cblxuXHQuZmlnID4gaW1nIHtcblx0XHR3aWR0aDogYXV0bztcblx0fVxuXHQudGV4dCB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cdFx0bWFyZ2luLWJvdHRvbTogMTBweDtcblx0fVxuXG5cdC5jb25maXJtIHtcblx0XHRwYWRkaW5nLWJvdHRvbTogMjBweDtcblx0XHRtYXJnaW4tYm90dG9tOiAyMHB4O1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdHRleHQtYWxpZ246IGNlbnRlcjtcblx0fVxuXG5cdGgyLCBoMywgcCB7XG5cdFx0bWFyZ2luOiAxMHB4IDQwcHg7XHRcblx0fVxuXG5cdGgxIHtcblx0XHRmb250LXNpemU6IDIuOGVtO1xuXHRcdHRleHQtYWxpZ246IGNlbnRlcjtcblx0XHRmb250LXdlaWdodDogNjAwO1xuXHRcdG1hcmdpbjogMCAwIDAuNWVtIDA7XG5cdH1cblx0XG5cdGgyIHtcblx0XHRtYXJnaW4tYm90dG9tOiAyMHB4O1xuXHR9XG5cblx0aDMge1xuXHRcdGZvbnQtd2VpZ2h0OiA2MDA7XG5cdH1cblxuXHRpbWcge1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdG1hcmdpbjogMCAwIDAgMDtcblx0fVxuXG5cblx0QG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG5cdFx0aDEge1xuXHRcdFx0Zm9udC1zaXplOiA0ZW07XG5cdFx0XHRtYXJnaW4tdG9wOiAyMHB4O1xuXHRcdH1cblx0fVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+QWl2byBqYSBMYXVyYSBwdWxtYWQ8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG5cdDxoMT57Y2hvb3NlUGx1cmFsKG5hbWVzLm5pbWkpfSB7dG9UaXRsZUNhc2UobmFtZXMubmltaSl9PC9oMT5cblxuXHQ8aW1nIGFsdD0nS3V0c2UgcGlsdCcgc3JjPSdrdXRzZS5wbmcnPlxuXG5cdDxkaXYgY2xhc3M9XCJkZXRhaWxzXCI+XG5cdFx0PGgyPlB1bG1hZGUgdG9pbXVtaW5lPC9oMj5cblx0XHQ8ZGl2IGNsYXNzPVwiZGV0YWlscy1jb2x1bW5zXCI+XG5cdFx0XHQ8ZGl2PlxuXHRcdFx0XHQ8aDM+TGF1bGF0dXM8L2gzPlxuXHRcdFx0XHQ8cD4xNTozMCAtIMOVbm5lcGFsZWUgKFDDpHJudSBtbnQgNjcsIFRhbGxpbm4pPC9wPlxuXHRcdFx0XHQ8cD4xNTo0NSAtIFBpbGRpc3RhbWluZSDDlW5uZXBhbGVlIHRyZXBpbC48L3A+XG5cdFx0XHRcdDxwPk3DpHJrdXMhIEp1dW5pIHNlaXN1Z2EgbHViYXRha3NlIGxhdWxhdHVzZSBydXVtaSBrdW5pIDMwIGluaW1lc3QhPC9wPlxuXHRcdFx0PC9kaXY+XG5cdFx0XHQ8ZGl2PlxuXHRcdFx0XHQ8aDM+UHVsbWFwaWR1PC9oMz5cblx0XHRcdFx0PHA+MTc6MDAgR2xlaG5pIGxvc3MgKFZhbmEtTXVzdGFtw6RlIDQ4LCBOw7VtbWUsIFRhbGxpbm4pPC9wPlxuXHRcdFx0XHQ8cD4xODowMCDDlWh0dXPDtsO2ay4gSsOkcmduZWIgbXV1c2lrYSwgdGFudHMgamEgdHJhbGwuPC9wPlxuXHRcdFx0XHQ8cD4wMTowMCBQZW8gb3JpZW50ZWVydXYgbMO1cHAuPC9wPlxuXHRcdFx0PC9kaXY+XG5cdFx0XG5cdFx0PC9kaXY+XG5cdFx0PGRpdiBjbGFzcz1cImljb25zLWNvbnRhaW5lclwiPlxuXHRcdFx0PGRpdiBjbGFzcz1cImljb25zXCI+XG5cdFx0XHRcdDxkaXYgY2xhc3M9XCJpY29uXCI+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cImZpZ1wiPlxuXHRcdFx0XHRcdFx0PGltZyBhbHQ9J3RzZXJlbW9vbmlhJyBzcmM9J3RzZXJlbW9vbmlhLnBuZyc+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cInRleHRcIj5cblx0XHRcdFx0XHRcdDxzcGFuPkxhdWxhdHVzPC9zcGFuPlxuXHRcdFx0XHRcdFx0PHNwYW4+MTU6MzA8L3NwYW4+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHQ8ZGl2IGNsYXNzPVwiaWNvblwiPlxuXHRcdFx0XHRcdDxkaXYgY2xhc3M9XCJmaWdcIj5cblx0XHRcdFx0XHRcdDxpbWcgYWx0PSd0ZXJ2aXR1c2pvb2snIHNyYz0ndGVydml0dXNqb29rLnBuZyc+XG5cdFx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cInRleHRcIj5cblx0XHRcdFx0XHRcdDxzcGFuPlRlcnZpdHVzam9vazwvc3Bhbj5cblx0XHRcdFx0XHRcdDxzcGFuPjE3OjE1PC9zcGFuPlxuXHRcdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0PGRpdiBjbGFzcz1cImljb25cIj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwiZmlnXCI+XG5cdFx0XHRcdFx0XHQ8aW1nIGFsdD0nw5VodHVzw7bDtmsnIHNyYz0nb2h0dXNvb2sucG5nJz5cblx0XHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0XHQ8ZGl2IGNsYXNzPVwidGV4dFwiPlxuXHRcdFx0XHRcdFx0PHNwYW4+w5VodHVzw7bDtms8L3NwYW4+XG5cdFx0XHRcdFx0XHQ8c3Bhbj4xODowMDwvc3Bhbj5cblx0XHRcdFx0XHQ8L2Rpdj5cblx0XHRcdFx0PC9kaXY+XG5cdFx0XHRcdDxkaXYgY2xhc3M9XCJpY29uXCI+XG5cdFx0XHRcdFx0PGRpdiBjbGFzcz1cImZpZ1wiPlxuXHRcdFx0XHRcdFx0PGltZyBhbHQ9J011dXNpa2EgamEgdGFudHMnIHNyYz0nbXV1c2lrYS5wbmcnPlxuXHRcdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHRcdDxkaXYgY2xhc3M9XCJ0ZXh0XCI+XG5cdFx0XHRcdFx0XHQ8c3Bhbj5Cw6RuZCwgdGFudHN1cMO1cmFuZDwvc3Bhbj5cblx0XHRcdFx0XHRcdDxzcGFuPjIwOjAwPC9zcGFuPlxuXHRcdFx0XHRcdDwvZGl2PlxuXHRcdFx0XHQ8L2Rpdj5cblx0XHRcdDwvZGl2PlxuXHRcdDwvZGl2PlxuXHQ8L2Rpdj5cblxuXHQ8ZGl2IGNsYXNzPVwiY29uZmlybVwiPlxuXHRcdDxoMj5Pc2FsZW1pc2VzdCB0ZWF2aXRhbWluZTwvaDI+XG5cdFx0PHA+w4RzamEgbcO2w7ZkdW51ZCBlcmlvbGx1a29ycmEgdMO1dHR1IG9uIHB1bG0gb24gcGxhbm5lcml0dWQgb2xlbWEgcGlnZW0gdsOkaWtlLiBLdXRzdW1lIHZhaWQgc3VndWxhc2kgbmluZyBsw6RoZWRhc2VtYWlkIHPDtXBydS48L3A+XG5cdFx0PGgzPlBhbHVuIHRlYXZpdGEgb21hIG9zYWxlbWlzZXN0IGVzaW1lc2VsIHbDtWltYWx1c2VsLCBzb292aXRhdmFsdCB2w6RoZW1hc3RpIGVubmUgMS4ganV1bGl0LjwvaDM+XG5cblx0PC9kaXY+XG5cblx0PGRpdiBjbGFzcz1cImhlcm9QaG90b1wiPlxuXHRcdDxpbWcgYWx0PSdBaXZvIGphIExhdXJhJyBzcmM9J3lsZW1pbmUuanBnJz5cblx0PC9kaXY+XG5cbjwvZGl2PlxuIl0sInNvdXJjZVJvb3QiOiIifQ==